# EnderUNIX Aget Makefile
# http://www.enderunix.org/aget/

OBJS = main.o Aget.o Misc.o Head.o Signal.o Download.o Resume.o
CFLAGS  = -g -W -DSOLARIS -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
LDFLAGS = -lpthread -lsocket -lnsl -lresolv
CC = gcc
STRIP=/usr/ccs/bin/strip

all: $(OBJS)
	$(CC) -o aget $(OBJS) $(LDFLAGS)

strip: $(all)
	$(STRIP) aget
	
install:
	cp -f aget /usr/local/bin/aget

clean: 
	rm -f aget *.o core.* *~
